server:
  port: 8801

spring:
  ## 引入：application-adminclient.yml配置文件
  profiles:
    include: adminclient,discovery,zipkin
  application:
    name: service-system

## 资源服务器配置
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://127.0.0.1:8101/user
      prefer-token-info: true

## 自定义属性配置
self:
  security:
    ## 是否启用安全配置
    enable: true
    anonUris: /favicon.ico,/actuator/**
    only-fetch-by-gateway: false
    scope: web
  doc:
    enable: true
    base-package: com.system.controller
    title: 系统微服务
    description: 系统微服务接口
    terms-of-service-url: "http://localhost:8801/"
    name: yuangy
    email: 1483782149@qq.com
    version: 0.0.1



